### PR TITLE
Converting Dictionary keys to string using TypeDescriptor

### PR DESCRIPTION
**Pull request by drcolombo**
This solves #546 as @xied75 suggested based on [http://stackoverflow.com/questions/393731/generic-conversion-function-doesnt-seem-to-work-with-guids](http://stackoverflow.com/questions/393731/generic-conversion-function-doesnt-seem-to-work-with-guids)

### CODE REVIEW

**Comment by xied75** [comment]
@drcolombo test failed, see here: https://travis-ci.org/mbdavid/LiteDB/jobs/225984649

**Comment by xied75** [comment]
Travis is not happy about your PR. You can click on the Details to see it.

**Comment by drcolombo** [comment]
Finally it's totally happy :) I forgot in the beginning about .NET Core - my apologies.

**Comment by Joy-less** [comment]
Closing in favour of #2568.

**Pull request closed without merging**
